SWBC.ImCovered.Web/SWBC.ImCovered.Web/Controllers/SiteController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Net.Mime;

namespace SWBC.ImCovered.Web.Controllers
{
    public class SiteController:
        BaseController
    {
        #region <Private members>

        private static readonly string _imageLogoPath;
        private static readonly string _defaultLogoImage;
        private readonly IHostingEnvironment _hostingEnvironment;

        #endregion

        #region <Constructors>

        static SiteController()
        {
            _imageLogoPath = "\\images\\logos\\";
            _defaultLogoImage = "imcovered_logo.png";
        }

        public SiteController(
            IHostingEnvironment pHostingEnvironment)
        {
            _hostingEnvironment = pHostingEnvironment ??
                throw new ArgumentNullException(
                    nameof(pHostingEnvironment));
        }

        #endregion

        [HttpGet]
        public IActionResult GetHeaderLogoUrl()
        {
            string imageMappedPath = Path
                .Combine(
                    _hostingEnvironment.WebRootPath,
                    _imageLogoPath);

            string logoFilename = _defaultLogoImage;

            logoFilename = Path.Combine(
                imageMappedPath,
                logoFilename);

            return (File(logoFilename, "image/png"));
        }
    }
}

SWBC.ImCovered.Web/SWBC.ImCovered.Web/Views/Shared/_dashboardLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - ImCovered</title>

    <!-- GLOBAL CSS: START -->
    <environment include="Development">
        <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/css/bootstrap.css")" />
        <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="@Url.Content("~/lib/bootstrap/css/bootstrap.min.css")"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        <link rel="stylesheet"
              href="@Url.Content("~/css/site.min.css")"
              asp-append-version="true" />
    </environment>
    <!-- GLOBAL CSS: STOP -->
    <!-- PAGE CSS: START -->
    @RenderSection("styles", required: false)
    <!-- PAGE CSS: STOP -->
</head>
<body class="dashboard">
    <header class="container-fluid">
        <div class="row align-items-center">
            <div class="logo-box col-10 col-sm-5 col-md-3 col-lg-3"
                 style="background-image: url('@Url.Action("GetHeaderLogoUrl","Site")');">
            </div>
        </div>
    </header>
    <div role="main"
         class="container-fluid">
        @RenderBody()
    </div>
    <footer>
        <div class="col-sm-6 col-md-5 col-lg-3">
            @await Component.InvokeAsync("FooterBuildInfoComponent")
        </div>
        @RenderSection("footer", required: false)
    </footer>

    <!-- GLOBAL SCRIPTS: START -->
    <environment include="Development">
        <script src="@Url.Content("~/lib/knockoutjs/knockout-latest.debug.js")"></script>
        <script src="@Url.Content("~/lib/jquery/jquery.js")"></script>
        <script src="@Url.Content("~/lib/bootstrap/js/bootstrap.js")"></script>
        <script src="@Url.Content("~/lib/fontawesome/all.js")"></script>
        <script src="@Url.Content("~/js/site.processed.js")" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js"
                asp-fallback-src="@Url.Content("~/lib/knockoutjs/knockout-latest.js")"
                asp-fallback-test="window.ko">
        </script>
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"
                asp-fallback-src="@Url.Content("~/lib/jquery/jquery.min.js")"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="@Url.Content("~/lib/bootstrap/js/bootstrap.bundle.min.js")"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM">
        </script>
        <script src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"
                asp-fallback-src="@Url.Content("~/lib/fontawesome/all.min.js")"
                asp-fallback-test="window.___FONT_AWESOME___"
                crossorigin="anonymous"
                integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ">
        </script>
        <script src="@Url.Content("~/js/site.min.js")" asp-append-version="true"></script>
    </environment>
    <!-- GLOBAL SCRIPTS: STOP -->
    <!-- PAGE SCRIPTS: START -->
    @RenderSection("scripts", required: false)
    <!-- PAGE SCRIPTS: END -->
</body>
</html>

SWBC.ImCovered.Web/SWBC.ImCovered.Web/Views/Shared/_layout.cshtml
<!DOCTYPE html>

<html class="unauth">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - ImCovered</title>

    <!-- GLOBAL CSS: START -->
    <environment include="Development">
        <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/css/bootstrap.css")" />
        <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="@Url.Content("~/lib/bootstrap/css/bootstrap.min.css")"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        <link rel="stylesheet"
              href="@Url.Content("~/css/site.min.css")"
              asp-append-version="true" />
    </environment>
    <!-- GLOBAL CSS: STOP -->
    <!-- PAGE CSS: START -->
        @RenderSection("styles", required: false)
    <!-- PAGE CSS: STOP -->
</head>
<body>
    <header class="container-fluid">
        <div class="row align-items-center">
            <div class="logo-box col-10 col-sm-5 col-md-3 col-lg-3"
                 style="background-image: url('@Url.Action("GetHeaderLogoUrl","Site")');">
            </div>
        </div>
    </header>
    <div role="main"
         class="container-fluid">
        @RenderBody()
    </div>
    <footer>
        <div class="col-sm-6 col-md-5 col-lg-3">
            @await Component.InvokeAsync("FooterBuildInfoComponent")
        </div>
        @RenderSection("footer", required: false)
    </footer>

    <!-- GLOBAL SCRIPTS: START -->
    <environment include="Development">
        <script src="@Url.Content("~/lib/knockoutjs/knockout-latest.debug.js")"></script>
        <script src="@Url.Content("~/lib/jquery/jquery.js")"></script>
        <script src="@Url.Content("~/lib/jquery-validation/jquery.validate.js")"></script>
        <script src="@Url.Content("~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js")"></script>
        <script src="@Url.Content("~/lib/bootstrap/js/bootstrap.bundle.js")"></script>
        <script src="@Url.Content("~/lib/fontawesome/all.js")"></script>
        <script src="@Url.Content("~/js/site.processed.js")" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js"
                asp-fallback-src="@Url.Content("~/lib/knockoutjs/knockout-latest.js")"
                asp-fallback-test="window.ko">
        </script>
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"
                asp-fallback-src="@Url.Content("~/lib/jquery/jquery.min.js")"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"
                asp-fallback-src="@Url.Content("~/lib/jquery-validation/jquery.validate.min.js")"
                asp-fallback-test="window.jQuery && window.jQuery.validator"
                crossorigin="anonymous"
                integrity="sha256-bu/BP02YMudBc96kI7yklc639Mu4iKGUNNcam8D2nLc=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="@Url.Content("~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js")"
                asp-fallback-test="window.jQuery && window.jQuery.validator"
                crossorigin="anonymous"
                integrity="sha256-9GycpJnliUjJDVDqP0UEu/bsm9U+3dnQUH8+3W10vkY=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="@Url.Content("~/lib/bootstrap/js/bootstrap.bundle.min.js")"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM">
        </script>
        <script src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"
                asp-fallback-src="@Url.Content("~/lib/fontawesome/all.min.js")"
                asp-fallback-test="window.___FONT_AWESOME___"
                crossorigin="anonymous"
                integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ">
        </script>
        <script src="@Url.Content("~/js/site.min.js")" asp-append-version="true"></script>
    </environment>
    <!-- GLOBAL SCRIPTS: STOP -->
    <!-- PAGE SCRIPTS: START -->
    @RenderSection("scripts", required: false)
    <!-- PAGE SCRIPTS: END -->
</body>
</html>